// Package twin implements the Twin Bridge WebSocket server. It receives events
// from a paired Chrome extension and aggregates them into Alerts that the
// digital twin (and MCP tools) can query.
//
// Architecture overview:
//
//	Chrome extension ──WS /twin──► TwinBridge
//	                               ├─ authenticates via token exchange (/pair)
//	                               ├─ stores events in AlertStore
//	                               ├─ triggers macOS notifications for high-priority events
//	                               └─ exposes health + discovery endpoints
//
// Security:
//   - Only connections from localhost (127.0.0.1 / ::1) are accepted.
//   - First WS message must be an auth message containing the session token.
//   - The session token is generated by /pair and written to the discovery file.
package twin

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/gorilla/websocket"
)

const (
	defaultPort       = 9800
	authTimeout       = 10 * time.Second
	readTimeout       = 60 * time.Second
	maxMessageBytes   = 64 * 1024 // 64 KiB per WS message
)

// Config holds configuration for the TwinBridge server.
type Config struct {
	// Port is the TCP port to listen on (default: 9800).
	Port int

	// MaxAlerts is the AlertStore ring-buffer capacity (default: 500).
	MaxAlerts int
}

// TwinBridge is the Twin Bridge WebSocket server.
type TwinBridge struct {
	cfg        Config
	store      *AlertStore
	meetings   *MeetingStore
	srv        *http.Server
	startAt    time.Time
	activePort int // port written to the discovery file (may differ from cfg.Port in integrated mode)

	mu    sync.RWMutex
	token string // current pairing token; empty means not paired

	db DBClient // optional — nil when Supabase is not configured
}

// DBClient is the minimal interface TwinBridge needs from the Supabase client.
type DBClient interface {
	Get(ctx context.Context, table string, query string) (json.RawMessage, error)
}

// upgrader accepts WebSocket upgrades only from localhost.
var upgrader = websocket.Upgrader{
	HandshakeTimeout: 5 * time.Second,
	ReadBufferSize:   4096,
	WriteBufferSize:  4096,
	CheckOrigin: func(r *http.Request) bool {
		return isLocalhost(r.RemoteAddr)
	},
}

// NewTwinBridge creates a TwinBridge with the given configuration.
func NewTwinBridge(cfg Config) *TwinBridge {
	if cfg.Port <= 0 {
		cfg.Port = defaultPort
	}
	return &TwinBridge{
		cfg:      cfg,
		store:    NewAlertStore(cfg.MaxAlerts),
		meetings: NewMeetingStore(),
	}
}

// SetDB wires the Supabase DB client so the bridge can serve /twin/domains.
func (tb *TwinBridge) SetDB(client DBClient) {
	tb.db = client
}

// Meetings returns the MeetingStore so MCP tools can query meeting sessions.
func (tb *TwinBridge) Meetings() *MeetingStore {
	return tb.meetings
}

// Store returns the underlying AlertStore so MCP tools can read alerts
// without going through the HTTP layer.
func (tb *TwinBridge) Store() *AlertStore {
	return tb.store
}

// Token returns the current pairing token. An empty string means the bridge
// has not been paired yet.
func (tb *TwinBridge) Token() string {
	tb.mu.RLock()
	defer tb.mu.RUnlock()
	return tb.token
}

// Init generates the initial pairing token, records the start time, and
// writes the discovery file. It must be called once before the bridge handles
// any requests — either by Start (standalone mode) or by the caller that uses
// RegisterRoutes (integrated mode).
//
// port is the port written to the discovery file so external tools can locate
// the bridge. In integrated mode this should be the main server port.
func (tb *TwinBridge) Init(port int) error {
	tok, err := generateToken()
	if err != nil {
		return fmt.Errorf("twin bridge: generate initial token: %w", err)
	}

	tb.mu.Lock()
	tb.token = tok
	tb.startAt = time.Now()
	tb.activePort = port
	tb.mu.Unlock()

	if err := writeDiscoveryFile(port, tok); err != nil {
		// Non-fatal — bridge can still operate without the discovery file.
		slog.Warn("twin bridge: failed to write discovery file", "error", err)
	}

	return nil
}

// RegisterRoutes registers all twin bridge HTTP handlers on an external mux.
// This allows the bridge to share the main server's port instead of running on
// its own listener. The caller is responsible for calling Init first.
//
// Routes registered:
//
//	GET /twin          — WebSocket endpoint
//	GET /twin/health   — Health check
//	GET /twin/pair     — Token pairing
func (tb *TwinBridge) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /twin/health", tb.HandleHealth)
	mux.HandleFunc("GET /twin/pair", tb.HandlePair)
	mux.HandleFunc("GET /twin", tb.HandleWS)
	mux.HandleFunc("POST /twin/push", tb.HandlePush)
	mux.HandleFunc("GET /twin/domains", tb.HandleDomains)
}

// HandleDomains returns the list of twin domains from the database.
// No authentication required — the extension reads this on startup.
//
//	GET /twin/domains
func (tb *TwinBridge) HandleDomains(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Access-Control-Allow-Origin", "*")

	if tb.db == nil {
		// DB not configured — return empty list so extension falls back to defaults
		w.Write([]byte(`[]`))
		return
	}

	data, err := tb.db.Get(r.Context(), "twin_domains",
		"enabled=eq.true&order=sort_order.asc&select=slug,name,host,origin,icon_url,category,reader_script,monitor_script,monitor_url,monitor_interval_min,chat_click_script,chat_read_script,chat_open_script,chat_send_script,contacts_script")
	if err != nil {
		slog.Warn("twin/domains: db error", "error", err)
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(`{"error":"db error"}`))
		return
	}

	w.Write(data)
}

// HandlePush receives browser events pushed by the Rust Desktop app and stores
// them in the AlertStore. This is the Go ↔ Rust integration point.
//
//   POST /twin/push
//   Content-Type: application/json
//   { "source": "slack", "event_type": "mention", "data": {...}, "timestamp": 1234567890, "origin": "desktop-bridge" }
func (tb *TwinBridge) HandlePush(w http.ResponseWriter, r *http.Request) {
	// Only accept from localhost
	if !isLocalhost(r.RemoteAddr) {
		http.Error(w, `{"error":"forbidden"}`, http.StatusForbidden)
		return
	}

	var payload struct {
		Source    string          `json:"source"`
		EventType string          `json:"event_type"`
		Data      json.RawMessage `json:"data"`
		Timestamp int64           `json:"timestamp"`
		Origin    string          `json:"origin"`
	}

	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte(`{"error":"invalid json"}`))
		return
	}

	if payload.Source == "" {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte(`{"error":"source required"}`))
		return
	}

	alert := Alert{
		ID:        uuid.New().String(),
		Source:    payload.Source,
		Type:      payload.EventType,
		Data:      payload.Data,
		CreatedAt: time.Now(),
		Read:      false,
	}

	tb.store.Add(alert)
	slog.Debug("twin push received", "source", payload.Source, "event_type", payload.EventType, "origin", payload.Origin)

	w.Header().Set("Content-Type", "application/json")
	w.Write([]byte(`{"ok":true}`))
}

// Start starts the bridge as a standalone HTTP server and writes the discovery
// file. It blocks until the server is shut down. This is kept for backward
// compatibility; prefer RegisterRoutes for integrated deployments.
func (tb *TwinBridge) Start() error {
	if err := tb.Init(tb.cfg.Port); err != nil {
		return err
	}

	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", tb.HandleHealth)
	mux.HandleFunc("GET /pair", tb.HandlePair)
	mux.HandleFunc("GET /twin", tb.HandleWS)

	tb.srv = &http.Server{
		Addr:              fmt.Sprintf("127.0.0.1:%d", tb.cfg.Port),
		Handler:           localhostOnly(mux),
		ReadHeaderTimeout: 5 * time.Second,
		IdleTimeout:       60 * time.Second,
	}

	slog.Info("twin bridge starting", "addr", tb.srv.Addr)

	if err := tb.srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		return fmt.Errorf("twin bridge: listen: %w", err)
	}
	return nil
}

// Shutdown gracefully stops the server and cleans up the discovery file.
func (tb *TwinBridge) Shutdown(ctx context.Context) error {
	defer removeDiscoveryFile()
	if tb.srv != nil {
		return tb.srv.Shutdown(ctx)
	}
	return nil
}

// ---------------------------------------------------------------------------
// HTTP Handlers (exported so they can be mounted on an external mux)
// ---------------------------------------------------------------------------

// HandleHealth returns a JSON health payload with uptime and alert count.
func (tb *TwinBridge) HandleHealth(w http.ResponseWriter, _ *http.Request) {
	tb.mu.RLock()
	uptime := time.Since(tb.startAt).Round(time.Second).String()
	tb.mu.RUnlock()

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"status": "ok",
		"uptime": uptime,
		"alerts": tb.store.Len(),
	})
}

// HandlePair generates a new session token, shows a macOS approval dialog,
// and returns the token on approval. The token is also persisted to the
// discovery file.
func (tb *TwinBridge) HandlePair(w http.ResponseWriter, r *http.Request) {
	if !isLocalhost(r.RemoteAddr) {
		http.Error(w, "forbidden", http.StatusForbidden)
		return
	}

	tok, err := generateToken()
	if err != nil {
		http.Error(w, "failed to generate token", http.StatusInternalServerError)
		return
	}

	// Show macOS approval dialog via osascript. On non-macOS systems (or if
	// osascript is unavailable) the dialog is skipped and pairing proceeds
	// automatically — useful for development / testing.
	approved := showPairingDialog()
	if !approved {
		slog.Info("twin bridge: pairing rejected by user")
		http.Error(w, "pairing rejected", http.StatusForbidden)
		return
	}

	tb.mu.Lock()
	tb.token = tok
	port := tb.activePort
	tb.mu.Unlock()

	if port == 0 {
		port = tb.cfg.Port
	}
	if err := writeDiscoveryFile(port, tok); err != nil {
		slog.Warn("twin bridge: pair — failed to update discovery file", "error", err)
	}

	slog.Info("twin bridge: paired", "remote", r.RemoteAddr)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{
		"token": tok,
	})
}

// HandleWS upgrades an HTTP connection to WebSocket and starts the event loop.
func (tb *TwinBridge) HandleWS(w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		slog.Warn("twin bridge: ws upgrade failed", "error", err, "remote", r.RemoteAddr)
		return
	}
	defer conn.Close()

	slog.Info("twin bridge: ws client connected", "remote", r.RemoteAddr)
	tb.handleConnection(conn)
	slog.Info("twin bridge: ws client disconnected", "remote", r.RemoteAddr)
}

// handleConnection authenticates a WebSocket connection and then processes
// events until the connection is closed.
func (tb *TwinBridge) handleConnection(conn *websocket.Conn) {
	conn.SetReadLimit(maxMessageBytes)

	// --- Auth phase ---
	if err := conn.SetReadDeadline(time.Now().Add(authTimeout)); err != nil {
		slog.Warn("twin bridge: set auth deadline failed", "error", err)
		return
	}

	_, raw, err := conn.ReadMessage()
	if err != nil {
		slog.Warn("twin bridge: auth read failed", "error", err)
		return
	}

	var msg authMessage
	if err := json.Unmarshal(raw, &msg); err != nil || msg.Type != "auth" {
		slog.Warn("twin bridge: invalid auth message")
		writeWSError(conn, "expected auth message")
		return
	}

	tb.mu.RLock()
	validToken := tb.token
	tb.mu.RUnlock()

	if validToken == "" || msg.Token != validToken {
		slog.Warn("twin bridge: auth token mismatch", "extension_id", msg.ExtensionID)
		writeWSError(conn, "invalid token")
		return
	}

	if msg.ExtensionID == "" {
		slog.Warn("twin bridge: missing extension_id")
		writeWSError(conn, "missing extension_id")
		return
	}

	// Auth succeeded — clear read deadline for normal operation.
	if err := conn.SetReadDeadline(time.Time{}); err != nil {
		slog.Warn("twin bridge: clear deadline failed", "error", err)
		return
	}

	slog.Info("twin bridge: extension authenticated", "extension_id", msg.ExtensionID)

	// Confirm auth success.
	writeWSJSON(conn, map[string]string{"type": "auth_ok"})

	// Register this connection as the active command target so MCP browser
	// tools can send bidirectional commands to the extension.
	cs := newCommandState(conn)
	setActiveState(cs)
	defer clearActiveState()

	// --- Event loop ---
	for {
		if err := conn.SetReadDeadline(time.Now().Add(readTimeout)); err != nil {
			slog.Warn("twin bridge: set read deadline failed", "error", err)
			return
		}

		_, raw, err := conn.ReadMessage()
		if err != nil {
			if websocket.IsUnexpectedCloseError(err,
				websocket.CloseGoingAway,
				websocket.CloseNormalClosure,
				websocket.CloseNoStatusReceived,
			) {
				slog.Warn("twin bridge: unexpected ws close", "error", err)
			}
			return
		}

		// Peek at the message type to route it correctly.
		var peek struct {
			Type string `json:"type"`
		}
		if err := json.Unmarshal(raw, &peek); err != nil {
			slog.Warn("twin bridge: malformed message", "error", err)
			continue
		}

		// Route command responses back to waiting callers.
		if peek.Type == "response" {
			var resp struct {
				ID     string          `json:"id"`
				Result json.RawMessage `json:"result"`
			}
			if err := json.Unmarshal(raw, &resp); err != nil {
				slog.Warn("twin bridge: malformed response", "error", err)
				continue
			}
			cs.handleCommandResponse(resp.ID, resp.Result)
			continue
		}

		// All other messages are treated as BridgeEvents (alerts).
		var event BridgeEvent
		if err := json.Unmarshal(raw, &event); err != nil {
			slog.Warn("twin bridge: malformed event", "error", err)
			continue
		}

		// Route meeting lifecycle events to the meeting session manager.
		// Captions stay local — they do NOT go into the alert store.
		switch event.Type {
		case "meeting_started":
			tb.HandleMeetingStarted(event)
			slog.Debug("twin bridge: meeting started", "source", event.Source)
			continue
		case "caption":
			tb.HandleCaption(event)
			// Captions are not stored as alerts (privacy-sensitive)
			continue
		case "meeting_ended":
			tb.HandleMeetingEnded(event)
			slog.Debug("twin bridge: meeting ended", "source", event.Source)
			// HandleMeetingEnded creates the meeting_summary alert — skip generic alert creation
			continue
		case "meeting_detected":
			// This is informational only (opt-in prompt was shown by service worker)
			slog.Debug("twin bridge: meeting detected", "source", event.Source)
			// Fall through to create a regular alert so the user can see it in twin_alerts
		case "twin_log":
			// Monitor data pushed from the extension — store in local alert store
			// and index in the local RAG system for the twin agent
			slog.Info("twin bridge: twin_log received", "source", event.Source)
			// Fall through to store in alert store
		}

		alert := Alert{
			ID:        uuid.New().String(),
			Source:    event.Source,
			Type:      event.Type,
			Data:      event.Data,
			CreatedAt: time.Now().UTC(),
			Read:      false,
		}
		tb.store.Add(alert)

		slog.Debug("twin bridge: event stored",
			"id", alert.ID,
			"source", alert.Source,
			"type", alert.Type,
		)

		// Trigger macOS notification for high-priority events.
		if shouldNotify(event) {
			title := fmt.Sprintf("Orchestra — %s", strings.Title(event.Source))
			body := fmt.Sprintf("New %s event", event.Type)
			go sendDesktopNotification(title, body)
		}
	}
}

// ---------------------------------------------------------------------------
// Pairing dialog
// ---------------------------------------------------------------------------

// showPairingDialog presents a macOS approval dialog asking the user to allow
// the Chrome extension to connect. Returns true if the user clicks "Allow".
// On systems without osascript the function returns true automatically.
func showPairingDialog() bool {
	script := `button returned of (display dialog "A Chrome extension wants to connect to Orchestra Desktop.\n\nAllow access?" buttons {"Deny", "Allow"} default button "Allow" with title "Orchestra Twin Bridge")`
	out, err := runOsascript(script)
	if err != nil {
		// osascript unavailable (non-macOS / headless) — auto-approve.
		slog.Info("twin bridge: osascript unavailable — auto-approving pair")
		return true
	}
	return strings.TrimSpace(out) == "Allow"
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// localhostOnly is an HTTP middleware that rejects non-localhost connections.
func localhostOnly(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !isLocalhost(r.RemoteAddr) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// isLocalhost returns true when addr is a loopback address (IPv4 or IPv6).
func isLocalhost(addr string) bool {
	host, _, err := net.SplitHostPort(addr)
	if err != nil {
		host = addr
	}
	ip := net.ParseIP(host)
	if ip == nil {
		return false
	}
	return ip.IsLoopback()
}

// writeWSError sends a JSON error message over the WebSocket connection.
func writeWSError(conn *websocket.Conn, msg string) {
	writeWSJSON(conn, map[string]string{"type": "error", "message": msg})
}

// writeWSJSON serialises v to JSON and sends it as a text WebSocket message.
func writeWSJSON(conn *websocket.Conn, v interface{}) {
	data, err := json.Marshal(v)
	if err != nil {
		slog.Warn("twin bridge: marshal ws message failed", "error", err)
		return
	}
	if err := conn.WriteMessage(websocket.TextMessage, data); err != nil {
		slog.Warn("twin bridge: write ws message failed", "error", err)
	}
}
