package twin

import (
	"encoding/json"
	"time"
)

// BridgeEvent is a raw event received from the Chrome extension over the
// Twin Bridge WebSocket connection.
type BridgeEvent struct {
	// Source identifies the originating extension module, e.g. "gmail", "github",
	// "slack", "calendar".
	Source string `json:"source"`

	// Type is the event kind, e.g. "dm", "mention", "pr_review", "meeting".
	Type string `json:"type"`

	// Data holds the event payload as raw JSON so handlers can unmarshal only
	// the fields they need.
	Data json.RawMessage `json:"data"`

	// Ts is the Unix millisecond timestamp when the event was generated by the
	// extension.
	Ts int64 `json:"ts"`
}

// Alert is a processed, persistent record derived from a BridgeEvent. Alerts
// are stored in the AlertStore and exposed via the twin_alerts MCP tool.
type Alert struct {
	// ID is a UUID generated when the alert is created.
	ID string `json:"id"`

	// Source mirrors BridgeEvent.Source.
	Source string `json:"source"`

	// Type mirrors BridgeEvent.Type.
	Type string `json:"type"`

	// Data is the original event payload.
	Data json.RawMessage `json:"data"`

	// CreatedAt is the server-side time the alert was stored.
	CreatedAt time.Time `json:"created_at"`

	// Read tracks whether the alert has been acknowledged.
	Read bool `json:"read"`
}

// authMessage is the first message a Chrome extension must send after opening
// a WebSocket connection to authenticate.
type authMessage struct {
	Type        string `json:"type"`
	Token       string `json:"token"`
	ExtensionID string `json:"extension_id"`
}
