[program:laravel-scheduler]
command=/bin/bash -c "while true; do php /opt/orchestra/web/artisan schedule:run --verbose --no-interaction >> /var/log/orchestra/scheduler.log 2>&1; sleep 60; done"
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/var/log/orchestra/scheduler-error.log
